version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senhasegura
    ports:
      - "5432:5432"
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    volumes:
       - pgadmin:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: